
# 名称
name: open-webui

# 版本
version: 0.1.124

# 镜像编译参数
docker:
  # 镜像名称
  image: snz1dp/open-webui
  # 镜像标签
  tag: 0.1.124
  # 编译文件
  file: Dockerfile
  # 目标平台
  platform:
  - linux/amd64
  - linux/arm64

# 服务定义
service:

  # 文件卷定义
  volumes:
  - data:/app/backend/data

  # 端口定义
  ports:
  - 8080:8080

  # 环境变量
  envs:
  - TZ=Asia/Shanghai
  - ENV=prod
  - USE_CUDA_DOCKER=false
  - USE_CUDA_DOCKER_VER=cu121
  - RAG_EMBEDDING_ENGINE=ollama
  - RAG_EMBEDDING_MODEL=shaw/dmeta-embedding-zh
  - OLLAMA_BASE_URL=http://ollama:11434
  - WEBUI_AUTH=false

  # 心跳检测
  healthcheck:
    url: /
    interval: 10s
    timeout: 10s
    period: 60s
    retries: 30

  # 路由定义
  ingress:
  - backend-port: 8080
    preserve-host: true
    strip-path: true
    sso:
    - /open-webui
